# Placeholder — overwritten by vpn/scripts/build-multi-subscription.sh
server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }
}
