services:
  xray:
    image: teddysun/xray:latest
    container_name: xray-reality-vless
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    ports:
      - "2053:2053/tcp"
    networks:
      - default
