#!/usr/bin/env bash
# Build Happ subscription: Hy2 nodes + RU-direct routing (body + HTTP header).
# Happ docs: routing via HTTP header `routing:` and/or happ:// link in body.
# "Update routing" checkbox needs a newer LastUpdated on the profile.
set -euo pipefail
STACK_DIR="${STACK_DIR:-/opt/personal-stack}"
HY2_DIR="$STACK_DIR/vpn/hysteria2"
SUB_DIR="$HY2_DIR/subscription"
SUB_FILE="$SUB_DIR/sub.txt"
SUB_PLAIN="$SUB_DIR/sub-plain.txt"
ROUTING_LINK_FILE="${ROUTING_LINK_FILE:-$STACK_DIR/vpn/routing/happ-ru-direct.link}"
NGINX_CONF="$HY2_DIR/nginx-sub.conf"

bash "$STACK_DIR/vpn/scripts/build-happ-routing.sh" --skip-reload

export STACK_DIR ROUTING_LINK_FILE SUB_FILE SUB_PLAIN NGINX_CONF
python3 << 'PY'
import os
import re
from pathlib import Path
from urllib.parse import quote

stack = Path(os.environ["STACK_DIR"])
hy2_dir = stack / "vpn/hysteria2"
sub_file = Path(os.environ["SUB_FILE"])
sub_plain = Path(os.environ["SUB_PLAIN"])
nginx_conf = Path(os.environ["NGINX_CONF"])
link_file = Path(os.environ["ROUTING_LINK_FILE"])
host = "89.124.70.216"
sni = "yandex.ru"

routing_deeplink = link_file.read_text(encoding="utf-8").strip()
if not routing_deeplink.startswith("happ://routing/"):
    raise SystemExit(f"Bad routing deeplink in {link_file}")
b64 = routing_deeplink.rsplit("/", 1)[-1]
if len(b64) % 4 != 0:
    raise SystemExit(f"Routing base64 not padded (len={len(b64)} mod4={len(b64) % 4})")


def hy2_uri(config_name: str, label: str) -> str:
    path = hy2_dir / config_name
    if not path.exists():
        return ""
    text = path.read_text()
    pwd_m = re.search(r'password:\s*"([^"]+)"', text)
    obfs_m = re.search(r'salamander:\s*\n\s*password:\s*"([^"]+)"', text)
    port_m = re.search(r"listen:\s*:(\d+)", text)
    if not pwd_m or not port_m:
        return ""
    pwd = quote(pwd_m.group(1), safe="")
    port = port_m.group(1)
    obfs = obfs_m.group(1) if obfs_m else ""
    pin = ""
    working = hy2_dir / "WORKING.txt"
    if working.exists():
        m = re.search(r"pinSHA256=([A-Fa-f0-9]+)", working.read_text())
        if m:
            pin = m.group(1)
    pin_q = f"&pinSHA256={pin}" if pin else ""
    obfs_q = f"&obfs=salamander&obfs-password={quote(obfs, safe='')}" if obfs else ""
    if not pin:
        raise SystemExit(
            f"Missing pinSHA256 in {hy2_dir / 'WORKING.txt'} — Happ 4.8+ requires pinnedPeerCertSha256"
        )
    return f"hysteria2://{pwd}@{host}:{port}/?sni={sni}{pin_q}{obfs_q}#{quote(label)}"


nodes: list[str] = []
for cfg, label in (
    ("config-36712.yaml", "Yandex-HY2-36712"),
    ("config-8443.yaml", "Yandex-HY2-8443"),
):
    uri = hy2_uri(cfg, label)
    if uri:
        nodes.append(uri)

if not nodes:
    raise SystemExit("No Hy2 nodes found")

# Official Happ body example: happ:// first, then node URIs.
# Meta lines use # prefix (app-management docs).
meta = [
    "#profile-title: base64:WWFuZGV4LUhZMg==",
    "#routing-enable: 1",
    "#include-all-networks-enable: true",
    "#exclude-local-networks-enable: true",
    "#exclude-apns-enable: true",
    "#subscription-ping-onopen-enabled: false",
]

with_routing = [
    *meta,
    routing_deeplink,
    "",
    *nodes,
]

plain = [
    "# Happ debug: nodes only, no routing",
    "#include-all-networks-enable: true",
    "#exclude-local-networks-enable: true",
    "#exclude-apns-enable: true",
    "",
    *nodes,
]

sub_file.parent.mkdir(parents=True, exist_ok=True)
sub_file.write_text("\n".join(with_routing) + "\n", encoding="utf-8")
try:
    sub_plain.write_text("\n".join(plain) + "\n", encoding="utf-8")
except PermissionError:
    print(f"WARN: cannot write {sub_plain}")

# nginx: official delivery is HTTP header `routing:`
escaped = (
    routing_deeplink.replace("\\", "\\\\")
    .replace('"', '\\"')
    .replace("$", "\\$")
)
nginx_conf.write_text(
    f"""# Generated by build-multi-subscription.sh — do not edit by hand.
server {{
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    types {{
        text/html html;
        text/plain txt link;
        application/json json;
    }}
    default_type text/plain;

    location = /sub.txt {{
        default_type text/plain;
        add_header routing "{escaped}" always;
        add_header routing-enable "1" always;
        add_header profile-title "base64:WWFuZGV4LUhZMg==" always;
        try_files /sub.txt =404;
    }}

    location = /sub-plain.txt {{
        default_type text/plain;
        try_files /sub-plain.txt =404;
    }}

    location = /routing/happ-ru-direct.link {{
        default_type text/plain;
        try_files /routing/happ-ru-direct.link =404;
    }}

    location / {{
        try_files $uri $uri/ =404;
    }}
}}
""",
    encoding="utf-8",
)

print(f"Wrote {sub_file} ({len(nodes)} nodes + onadd)")
print(f"Wrote {nginx_conf}")
PY

echo "==> Reload subscription nginx"
cd "$HY2_DIR"
docker compose up -d hy2-subscription --force-recreate
sleep 1

echo "==> Verify"
echo "-- headers --"
curl -fsSI "http://127.0.0.1:8888/sub.txt" | grep -iE '^(HTTP|routing|routing-enable)' || true
echo "-- body head --"
curl -fsS "http://127.0.0.1:8888/sub.txt" | head -12
echo "-- decode check --"
python3 - <<'PY'
import base64, json, urllib.request
req=urllib.request.Request("http://127.0.0.1:8888/sub.txt")
with urllib.request.urlopen(req) as r:
    headers={k.lower():v for k,v in r.headers.items()}
    body=r.read().decode()
h=headers.get("routing","")
print("header_routing", "yes" if h.startswith("happ://routing/") else "NO", "len", len(h))
line=next((l for l in body.splitlines() if l.startswith("happ://routing/")), "")
b64=line.rsplit("/",1)[-1]
json.loads(base64.b64decode(b64))
print("body_routing_ok", bool(line), "b64_mod4", len(b64)%4)
PY
